[project]
name = "backend"
version = "0.1.2"
description = "My personal web laboratory"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jinja2>=3.1.6",
    "markdown>=3.8",
    "rich>=14.0.0",
    "robyn>=0.66.2",
]
