[project]
name = "backend"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["jinja2>=3.1.6", "markdown>=3.8", "passlib>=1.7.4", "robyn>=0.66.2"]
